spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydata?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: book.pojo

server:
  port: 9000